FROM python:3.9

#RUN adduser --uid 1000 --disabled-password test_user
#USER test_user


# setup python
#RUN apt-get update
#RUN apt-get -y install locales && \
#    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
#RUN apt-get install -y vim less supervisor

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

WORKDIR /code
COPY requirements.txt /code
COPY scripts/supervisord_web.conf /code/scripts
COPY scripts/supervisord_worker.conf /code/scripts

COPY scripts/setup_python.sh /tmp/
RUN /tmp/setup_python.sh

#RUN pip install --upgrade pip
#RUN pip install --upgrade setuptools
#RUN pip install -r requirements.txt

# setup java
#FROM openjdk:11-slim

# setup nodejs
#RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

#RUN nvm install --lts