version: '3'
services:
  python:
    build: .
    tty: true
    ports:
      - "5001:5000"
    volumes:
      - .:/code
      - ./logs:/logs
    command: /bin/bash -c "/code/scripts/clean_logs.sh && /usr/bin/supervisord -c /code/supervisord.conf"
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672
      - RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
      - C_LOG_WIDTH=100
    links:
      - postgresql
      - redis
      - elasticsearch
    depends_on:
      - redis
      - rabbitmq
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_PASSWORD=P@ssw0rd
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=P@ssw0rd
    depends_on:
      - elasticsearch
  
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    
  #monitor:
  #  image: python
  #  tty: true
  #  container_name: celery_monitor
  #  ports:
  #    - 5555:5555
  #  command:  flower -A tasks --port=5555 --broker=redis://redis:6379/0
  #  depends_on:
  #    - python
  #    - redis
  
  postgresql:
    build: ./postgresql
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  flower:
    restart: "always"
    image: mher/flower:0.9.7
    command: --broker=amqp://guest:guest@rabbitmq:5672// --broker_api=http://guest:guest@rabbitmq:5671/api/
    ports:
      - "5501:5555"
    links:
      - rabbitmq

volumes:
  elasticsearch-data:
    driver: local