version: "3.7"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    volumes:
      - type: bind
        source: .
        target: /code