version: '3'
services:

  
  python:
    build: 
      context: .
      dockerfile: ./python/Dockerfile
    tty: true
    ports:
      - "5001:5000"
    volumes:
      - ./python/src:/code
    links:
      - redis
    
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"